### ISSUE TITLE
Citizens does not have settings

### ISSUE THREAD

**Issue by tdybda17** [aau-giraf/api_client#23]
Right now the `GirafUserModel` has a relation to `SettingsModel` but it should be the citizens who have the relation to `SettingsModel`. This is an issue due to [weekplaner#15](https://github.com/aau-giraf/weekplanner/issues/15) where the giraf users would like to change the number of days to display in the weekplan screen for each citizen, separately.

**Comment by Lortemanden** [comment]
It should be guardians who can change citizen settings. Citizens should not be able to change their settings themself.

**Comment by jrodel17** [comment]
** Related to issue no. 323** (Can't link to issues in other repos)

**Comment by TobiasNielsen** [comment]
This issues is resolved on web_api https://github.com/aau-giraf/web-api/issues/64
Such that the server does not allow a citizen to change their settings.
