### ISSUE TITLE
Fix failing tests

### ISSUE THREAD

**Issue by Laexander** [aau-giraf/api_client#33]
2 tests for the api_client fails (see attached image), this should be fixed.

![Failing_tests](https://user-images.githubusercontent.com/17495079/77415187-5ed01680-6dc2-11ea-9f75-9943c1a83d5c.png)

**Comment by joandrsn** [comment]
https://github.com/aau-giraf/api_client/blob/342a0bf2fc8ffed67588aa19baa884b0b95def36/test/persistence/persistence_test.dart

**Comment by Seraph2** [comment]
The error does not seem to occur anymore, after having spoken to Laexander. I will close the issue.
