### ISSUE TITLE
Unneccesary test dependencies in pictogram_api_test.dart

### ISSUE THREAD

**Issue by jrodel17** [aau-giraf/api_client#37]
**Describe the bug**
Related to issue #2 

In pictogram_api_test.dart in the API folder inside the test folder, the test 'Get raw image' is dependent on the image that the 'Updates pictogram image' test updates. 

The ladder instantiates an image with certain byte values, that the former tests against. I believe this is a bad way to do it, since one test might fail for reasons unrelated to the other test, but still causing the other test to fail.

**Expected behavior**
Either make the tests as dependent tests (If possible in flutter/dart) or possibly create that image in the setup in the beginning before running tests.

**Actual behavior**
The image is instantiated in the API in a previous test case.

**Screenshots**
I marked with yellow where the raw bytes are instantiated and the grams list, the getter in 'Get raw image' uses to obtain the image, which the 'Updates pictogram image' test updates. Marked with red is where the byte values are tested against eachother.

![download (1)](https://user-images.githubusercontent.com/34282060/78031436-d6beb380-7363-11ea-836e-98de6d0983f5.png)

**Comment by joandrsn** [comment]
@jrodel17 There is not a dependency problem between these two images tests.

Each have their own image defined.
So is the issue that you would ask for the image to be a global variable?

**Comment by joandrsn** [comment]
As a screenshot with an extra test added to prove there is not a dependency problem

![image](https://user-images.githubusercontent.com/5766695/78129863-8a817b00-7418-11ea-8fd0-8f729911ccd0.png)

**Comment by jrodel17** [comment]
@joandrsn When are the bytes set for the image pointed to by the id from grams[0].id?

imagebytes is instantiated with certain byte values in the test for get image. It is matched up against image bytes uptained by calling the getImage on the grams[0].id which is instantiated in the beginning of the file, but I don't see any image there. Then when I spoke to Jonas Krogh, as I understood it, the image that getImage obtains, gets instantiated during the updates pictogram image test. Thats why I talked about them being dependent in an unfortunate way.

If this is not the case, then where do the image bytes from the getImage, that you call your expect method on in the test get set? I mean they would be set somewhere to something that you know should be the same as what you instantiate locally in the test. I just don't see it anywhere, and then was told that it was the previous test method that instantiated that image or the imagebytes.

**Comment by joandrsn** [comment]
@jrodel17 Ah that why.

The httpMock function simulates the API on the URL '/${id}/image/raw'. It does not matter what the `${id}` is, as long as they're the same in both `getImage(${id})` and `expectOne(url: '/${id}/image/raw'...`.

I could just as well had simply written a `1` or another integer - it would still function. 

As far as I can tell, the client first search in the `Pictogram` endpoint for metadata about the image. After they have found some ID's that they need, it's the clients job to request the actual image.

**Comment by jrodel17** [comment]
Talked with @joandrsn and I misunderstood something in the code. Therefore there is actually no issue and I will close it.
