### ISSUE TITLE
Fundamental bug in the offline repository

### ISSUE THREAD

**Issue by tdybda17** [aau-giraf/api_client#52]
**Describe the bug**
Models are stored in plain `.json` format in the offline repository which can produce unexpected behavior when reference models are updated or deleted.

Say an `Activity` with `offline_id = 45` is saved in the offline repository with a pictogram with `offline_id = 34`:
```
{
    "id": "1",
    "order": "20",
    "pictogram": {
        "id": "2"
    }
}
```

If then the pictogram were to be deleted with
```
PictogramModel.offline().delete(34)
```

Then calling `ActivityModel.offline().get(45)` will still return the activity with the deleted picogram.

**To Reproduce**
1. Insert an activity to the repository
2. Delete its pictogram
3. Get the activity again
4. Notice that the pictogram is still there

**Expected behavior**
Activity should not get the deleted pictogram with it.

**Actual behavior**
Activity gets the deleted pictogram with it.

**Comment by Riasalit** [comment]
This issue does not exist anymore as all previous offline functionality was removed by 2020f
