### ISSUE TITLE
As a developer I need code infrastructure for a local database and model adapters in order to implement offline functionality

### ISSUE THREAD

**Issue by Riasalit** [aau-giraf/api_client#72]
Is your feature request related to a problem? Please describe.
An Infrastructure to be able to use local database in offline mode needs to be implemented in order to further develop on the offline implementation.
Link to issues:
aau-giraf/weekplanner/issues/9
aau-giraf/weekplanner/issues/389

Describe the solution you'd like
Suggestion https://aau-giraf.github.io/wiki/Handover/2020E/Issues/offline_mode/

Describe alternatives you've considered
SQLite (sqflite til flutter) could be used for the local database

**Comment by JakobTopholt** [comment]
Related issues:

https://github.com/aau-giraf/weekplanner/issues/414
https://github.com/aau-giraf/weekplanner/issues/415
https://github.com/aau-giraf/weekplanner/issues/408
