### ISSUE TITLE
As a developer I would like an interface for the offline features

### ISSUE THREAD

**Issue by Kaliahh** [aau-giraf/api_client#80]
**Is your feature request related to a problem? Please describe.**
At the moment, only one group can work on the offline mode at the same time. 

**Describe the solution you'd like**
An interface would allow the work to be spread out to more groups

Related to #52 and #72 (And aau-giraf/weekplanner#9)

**Comment by Riasalit** [comment]
Completed with pull request #83, Closes didnt link the issue for some reason.
